### ISSUE TITLE
Vegalite warnings in in data_statistical_packages

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#809]
```
TypeError: Cannot read property 'getContext' of null
    at resize (/home/ubuntu/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-scenegraph/build/vega-scenegraph.js:3377:26)
    at CanvasRenderer.prototype$6.resize (/home/ubuntu/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-scenegraph/build/vega-scenegraph.js:3427:5)
    at CanvasRenderer.prototype$4.initialize (/home/ubuntu/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-scenegraph/build/vega-scenegraph.js:2989:17)
    at CanvasRenderer.prototype$6.initialize (/home/ubuntu/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-scenegraph/build/vega-scenegraph.js:3422:28)
    at initializeRenderer (/home/ubuntu/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-view/build/vega-view.js:630:8)
    at renderHeadless (/home/ubuntu/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-view/build/vega-view.js:736:12)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async View.renderToCanvas [as toCanvas] (/home/ubuntu/.julia/packages/VegaLite/sHyyT/deps/node_modules/vega-view/build/vega-view.js:771:15)
```

**Comment by jlperla** [comment]
this might be a case where we just want to use that jupinx tag to prune the output text if it is easy?
